### ISSUE TITLE
true normals of Heart polynomial shape looks bad (with generic2DNormalEstimators)

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtalTools#261]
by using:
`generic3dNormalEstimators -p "-1*(x^2+2.25*y^2+z^2-1)^3+x^2*z^3+0.1125*y^2*z^3"  -a -10 -A 10 -e True   -V Normals -g 0.02`
we obtain:
<img width="912" alt="capture d ecran 2016-05-16 a 11 33 35" src="https://cloud.githubusercontent.com/assets/772865/15285846/1034cc82-1b5a-11e6-8924-223ce622095c.png">
(it looks located near the 0 of Z axis)

**Comment by JacquesOlivierLachaud** [comment]
Well. It is not really bug. It is because of the involved polynomial and of the Newton algorithm to look for the correct surface intersection (i.e. P(x,y,z)=0). Signs are bad around this zone, so projection and normals are badly approximated. I need to implement more complex root search algorithm to get rid of this bug.

**Comment by JacquesOlivierLachaud** [comment]
More precisely, there are several surfaces P=0 around these places, and the "bad ones" may be the ones closest to the digital surface.

**Comment by kerautret** [comment]
ok thanks, else on the other shapes it looks fine, so perhaps not very urgent ;)
